demoDocker4/Models/CompanyForCreationDto.cs
namespace demoDocker4.Models
{
    public class CompanyForCreationDto
    {
        public string? Name { get; set; }
        public string? Address { get; set; }
        public string? Country { get; set; }
    }
}

demoDocker4/Models/CompanyForUpdateDto.cs
namespace demoDocker4.Models
{
    public class CompanyForUpdateDto
    {
        public string? Name { get; set; }
        public string? Address { get; set; }
        public string? Country { get; set; }
    }
}

demoDocker4/Models/CreateSuperHeroDto.cs
namespace demoDocker4.Models
{
    public class CreateSuperHeroDto
    {
        public string Name { get; set; } = string.Empty;
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public string Place { get; set; } = string.Empty;
    }
}

demoDocker4/Models/ErrorViewModel.cs
namespace demoDocker4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

demoDocker4/Controllers/CompanyController.cs
using demoDocker4.Db;
using demoDocker4.Models;
using demoDocker4.Repo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace demoDocker4.Controllers
{

    public class CompanyController : Controller
    {

        private readonly ICompanyRepo _companyRepo;

        public CompanyController(ICompanyRepo companyRepo)
        {
            _companyRepo = companyRepo;
        }

        [HttpGet]
        public ActionResult<IEnumerable<Company>> GetCompanies()
        {
            IEnumerable<Company> companies = _companyRepo.GetCompanies();

            return View(companies);
        }


      //  [HttpGet("{id}", Name = "CompanyById")]
      //  public async Task<IActionResult> GetCompany(int id)
      //  {
      //      var company = await _companyRepo.GetCompany(id);
      //      if (company is null) return NotFound();
      //      return Ok(company);
      //  }

      //  [HttpPost]
      //  public async Task<IActionResult> CreateCompany(
      //      [FromBody] CompanyForCreationDto company)
      //  {
      //      var createCompany = await _companyRepo.CreateCompany(company);
      //      return CreatedAtRoute(
      //"CompanyById",
      //  routeValues: new { id = createCompany.Id },
      //  createCompany);
      //  }

      //  [HttpPut("{id}")]
      //  public async Task<IActionResult> UpdateCompany(
      //   int id,
      //   [FromBody] CompanyForUpdateDto company)
      //  {
      //      var dbCompany = await _companyRepo.GetCompany(id);
      //      if (dbCompany is null)
      //      {
      //          return NotFound();
      //      }

      //      await _companyRepo.UpdateCompany(id, company);

      //      return NoContent();
      //  }

      //  [HttpDelete("{id}")]
      //  public async Task<IActionResult> DeleteCompany(int id)
      //  {
      //      var dbCompany = await _companyRepo.GetCompany(id);
      //      if (dbCompany is null)
      //      {


      //          return NotFound();
      //      }

      //      await _companyRepo.DeleteCompany(id);

      //      return NoContent();
      //  }

      //  [HttpGet("ByEmployeeId/{id}")]
      //  public async Task<IActionResult> GetCompanyForEmployee(int id)
      //  {
      //      var company = await _companyRepo.GetCompanyByEmployeeId(id);
      //      if (company is null)
      //      {
      //          return NotFound();
      //      }

      //      return Ok(company);
      //  }

      //  // 
      //  [HttpGet("{id}/multipleResult")]
      //  public async Task<IActionResult> GetMultipleResults(int id)
      //  {
      //      var company = await _companyRepo.GetMultipleResults(id);
      //      if (company is null)
      //      {
      //          return NotFound();
      //      }

      //      return Ok(company);
      //  }

      //  ///
      //  [HttpGet("MultipleMapping")]
      //  [Authorize]
      //  public async Task<IActionResult> GetMultipleMapping(int id)
      //  {
      //      var companies = await _companyRepo.MultipleMapping();
      //      return Ok(companies);
      //  }
    }
}

demoDocker4/Controllers/HomeController.cs
using demoDocker4.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace demoDocker4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

demoDocker4/Views/Company/GetCompanies.cshtml
@model IEnumerable<demoDocker4.Db.Company>

@{
    ViewData["Title"] = "GetCompanies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>GetCompanies</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

demoDocker4/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>name: gog</h1>
<h1>age: 15</h1>
<h1>country: JP</h1>

demoDocker4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hello</h1>
</div>

demoDocker4/Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Test</h1>
<h3>测试</h3>
<table>
    <tr>
        <td>ID</td>
        <td>Ad</td>
        <td>Department</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Murat</td>
        <td>Yazilzm</td>
    </tr>
</table>

demoDocker4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - demoDocker4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/demoDocker4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">demoDocker4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">首页</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">关于</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="GetCompanies">CompanyDemo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Yotoro - <a asp-area="" asp-controller="Home" asp-action="About">关于</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>